### ISSUE TITLE
Non ASCII characters raises errors

### ISSUE THREAD

**Issue by ptgreg** [syrusakbary/snapshottest#16]
Hello,

In version 0.5.0

This just doesn't work:
```
def simple_test(self):
        expect = u'pépère'
        self.assertMatchSnapshot(expect)
```
and fails with this error:
```
ERROR: test suite for <class 'alk_service_search.tests.controller.search.v1.test_advanced_search.AdvancedSearchMixinTestCase'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 228, in run
    self.tearDown()
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/suite.py", line 367, in teardownContext
    try_run(context, names)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/nose-1.3.6-py2.7.egg/nose/util.py", line 471, in try_run
    return func()
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/unittest.py", line 81, in tearDownClass
    module.save()
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/module.py", line 145, in save
    snapshots_declarations.append('''snapshots['{}'] = {}'''.format(key, pretty(value)))
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 30, in __call__
    return self.format(value, self.indent)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 45, in format
    return self.format_str(value, indent)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 56, in format_str
    return repr(str(value))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
```

and If I just do 
```
def simple_test(self):
        expect = 'pépère'
        self.assertMatchSnapshot(expect)
```
it saves the snapshot on disc 
`snapshots['AdvancedSearchMixinTestCase::simple_test 1'] = 'p\xc3\xa9p\xc3\xa8re'`
but fails when running nose to check
```
ERROR: simple_test (alk_service_search.tests.controller.search.v1.test_advanced_search.AdvancedSearchMixinTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ptgreg/alkemics/dev/backend/service-search-es/alk_service_search/tests/controller/search/v1/test_advanced_search.py", line 27, in simple_test
    self.assertMatchSnapshot(expect)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/unittest.py", line 105, in assert_match_snapshot
    self._snapshot.assert_match(value)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/module.py", line 225, in assert_match
    PrettyDiff(prev_snapshot, self)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/unittest.py", line 29, in assert_equals
    self.assertEqual(value, snapshot)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/unittest.py", line 74, in comparePrettyDifs
    raise self.failureException('\n'.join(diff_report(obj1, obj2)))
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/reporting.py", line 50, in diff_report
    ] + left.get_diff(right)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/diff.py", line 40, in get_diff
    text2 = ['Snapshot ', ''] + self.pretty(other).splitlines(1)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 30, in __call__
    return self.format(value, self.indent)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 37, in format
    return self.format(value.obj, indent)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 45, in format
    return self.format_str(value, indent)
  File "/Users/ptgreg/.virtualenvs/search-es/lib/python2.7/site-packages/snapshottest/formatter.py", line 56, in format_str
    return repr(str(value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
-------------------- >> begin captured logging << --------------------
ddtrace.encoding: DEBUG: using Msgpack encoder
pip.utils: DEBUG: lzma module is not available
pip.vcs: DEBUG: Registered VCS backend: git
pip.vcs: DEBUG: Registered VCS backend: hg
pip.vcs: DEBUG: Registered VCS backend: svn
pip.vcs: DEBUG: Registered VCS backend: bzr
--------------------- >> end captured logging << ---------------------
```

**Comment by tupy** [comment]
@syrusakbary @jsep please, create a new release to fix this issue.

**Comment by adkl** [comment]
I still have this error. I'm using version 0.5.0

**Comment by ygormutti** [comment]
@adkl this was fixed in master, but we need to bump the version and publish it to PyPI. Right now you can use the commit hash in you `requirements.txt` or `Pipfile`.

@yourbuddyconner do you have credentials to push an update to PyPI? cc @syrusakbary

**Comment by yourbuddyconner** [comment]
@ygormutti I do not, @syrusakbary will have to add my user `yourbuddyconner` to the repository ownership on PyPi.

**Comment by yourbuddyconner** [comment]
Closing as fixed.
