### ISSUE TITLE
0.5.1 Breaks tests

### ISSUE THREAD

**Issue by hobochild** [syrusakbary/snapshottest#95]
After upgrading from 0.5.0 -> 0.5.1, it looks like the value in the snapshot is being returning as non-serializable generator? 

```
    def assert_equals(self, value, snapshot):
>       assert value == snapshot
E       assert <[TypeError("...x7f40bc5cd3f8> == [{'geometry': ...': 'Feature'}]
E         (pytest_assertion plugin: representation of details failed.  Probably an object has a faulty __repr__.)
E         /home/app/.local/share/virtualenvs/app-4PlAip0Q/lib/python2.7/site-packages/simplejson/encoder.py:273: TypeError: Object of type generator is not JSON serializable
```

```
E       assert <[TypeError("...x7f40c119aab8> == {'features': [...reCollection'}
E         Omitting 1 identical items, use -vv to show
E         Differing items:
E         {'features': <generator object <genexpr> at 0x7f40bc63fb90>} != {'features': [{'geometry': {'coordinates': [-0.077092051506, 51.5275860195], 'type': 'Point'}, 'properties': {'name': ..., ...], 'type': 'LineString'}, 'properties': {'distance': 608.4, 'duration': 60.0, 'name': 'Raw'}, 'type': 'Feature'}]}
E         Use -v to get the full diff
``` 

Anyone found a fix?

**Comment by BenjamenMeyer** [comment]
I had some kind of similar issue that cropped up under Django leading:
```
  File "~/.pyenv/shims/python/lib/python3.7/site-packages/rest_framework/utils/serializer_helpers.py", line 19, in __init__
    self.serializer = kwargs.pop('serializer')
KeyError: 'serializer'
```
Doing a `python migrate test --snapshot-update` then put `ErrorDetail` (see https://github.com/encode/django-rest-framework/issues/6032) into the snapshots. When downgrading to 0.5.0 the issue went away.

**Comment by StoicLoofah** [comment]
I'll note that I'm also still having this issue when using snapshots with DRF. I was able to work around it by casting the serializer data as `dict`, but it is more cumbersome

**Comment by paulmelnikow** [comment]
It could be useful to see if this problem has been fixed in the master branch. I'd like to publish it to PyPI, but need @syrusakbary to give me access to do that.

**Comment by StoicLoofah** [comment]
> It could be useful to see if this problem has been fixed in the master branch. I'd like to publish it to PyPI, but need @syrusakbary to give me access to do that.

I ran into this using ea48109b4ff98529cc7e9331b49fea6b4220929f (rather than using what's on pypi), so I think this is still happening, but I also see something just went in 6 minutes ago, so I would have to check again

**Comment by paulmelnikow** [comment]
Okay, then it's probably not fixed. A PR to fix this issue would be welcome!

**Comment by paulmelnikow** [comment]
@hobochild Are you using Django Rest Framework too?

**Comment by hobochild** [comment]
> @hobochild Are you using Django Rest Framework too?

No we are using Flask

**Comment by paulmelnikow** [comment]
I think reproducible test cases here would be really helpful 🙌🏼

**Comment by StoicLoofah** [comment]
@paulmelnikow I was able to reproduce in a slimmed down version of this repo, but i'm not sure if this is actually what you're looking for. I installed the latest Django Rest Framework and snapshottest to get the following requirements

```
asgiref==3.2.10
Django==3.1.2
djangorestframework==3.12.1
fastdiff==0.2.0
pytz==2020.1
six==1.15.0
snapshottest==0.6.0
sqlparse==0.4.1
termcolor==1.1.0
wasmer==0.4.1
```

I then setup a test app (following the [Django tutorial](https://docs.djangoproject.com/en/3.1/intro/tutorial01/)) with

```
django-admin startproject mysite
python manage.py startapp polls
```

Added polls and snapshot test to my settings, then added the following into the polls app

models.py
```
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
```

serializers.py
```
from rest_framework import serializers

from . import models

class QuestionSerializer(serializers.ModelSerializer):

    class Meta:
        model = models.Question
        fields = ('id', 'question_text', )
```

tests.py
```
from snapshottest.django import TestCase

from . import models, serializers


# Create your tests here.

class SerializerTestCase(TestCase):
    def test_serializer(self):
        question = models.Question.objects.create(question_text='My Test Text')
        serializer = serializers.QuestionSerializer(question)
        self.assertMatchSnapshot(serializer.data)
```

The test passes on snapshot creation or using `--snapshot-update`, but if I run the test to compare against the snapshot, I get

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_serializer (polls.tests.SerializerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevinleung/snapshottest95/mysite/polls/tests.py", line 12, in test_serializer
    self.assertMatchSnapshot(serializer.data)
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/unittest.py", line 105, in assert_match_snapshot
    self._snapshot.assert_match(value, name=name)
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/module.py", line 247, in assert_match
    self.assert_value_matches_snapshot(value, prev_snapshot)
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/module.py", line 230, in assert_value_matches_snapshot
    formatter.assert_value_matches_snapshot(self, test_value, snapshot_value, Formatter())
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/formatters.py", line 20, in assert_value_matches_snapshot
    test.assert_equals(formatter.normalize(test_value), snapshot_value)
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/formatter.py", line 24, in normalize
    return formatter.normalize(value, self)
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/snapshottest/formatters.py", line 47, in normalize
    return value.__class__([formatter.normalize(item) for item in iterator])
  File "/Users/kevinleung/snapshottest95/lib/python3.6/site-packages/rest_framework/utils/serializer_helpers.py", line 17, in __init__
    self.serializer = kwargs.pop('serializer')
KeyError: 'serializer'

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
Destroying test database for alias 'default'...

======================================================================
SnapshotTest summary
----------------------------------------------------------------------
1 snapshots passed.
======================================================================
```

To save you the lookup, the problem appears to be trying to run a snapshot against the [ReturnDict](https://github.com/encode/django-rest-framework/blob/79c37d0dc3740aa1c439f8a447e5e8b64fd567be/rest_framework/utils/serializer_helpers.py#L17) class in DRF. The `CollectionFormatter` is trying to invoke the constructor for `ReturnDict`, but the constructor for `ReturnDict` actually has extra required arguments.

As I mentioned above, I was able to work around it by casting e.g. `self.assertMatchSnapshot(dict(serializer.data))`. Not a huge deal but worth pointing out

Also I see that the issue that @BenjamenMeyer and I are having appears to be different from @hobochild so I'm happy to move this to a separate issue or otherwise make sure these are tracked separately

**Comment by StoicLoofah** [comment]
Oh, perhaps the thing to do is to register a custom formatter for `ReturnDict` using https://github.com/syrusakbary/snapshottest/blob/48528b7679987c979c9fa4b8af1e57db601fdb2f/snapshottest/formatter.py#L36 in my app?

**Comment by StoicLoofah** [comment]
I was able to fix it by adding the following into my `conftest.py`

```
from rest_framework.utils.serializer_helpers import ReturnDict, ReturnList
from snapshottest import formatter, formatters

class DrfReturnCollectionFormatter(formatters.TypeFormatter):
    def normalize(self, value, formatter):
        iterator = iter(value.items()) if isinstance(value, dict) else iter(value)
        # Added the serializer kwarg as required by ReturnDict or ReturnList
        return value.__class__([formatter.normalize(item) for item in iterator],
                               serializer=None)

formatter.Formatter.register_formatter(DrfReturnCollectionFormatter(ReturnDict,
                                                                    formatters.format_dict))
formatter.Formatter.register_formatter(DrfReturnCollectionFormatter(ReturnList,
                                                                    formatters.format_list))
```

Not sure how you guys want to handle this since it's an upstream issue but figured I would let you know how I addressed it!

**Comment by medmunds** [comment]
@StoicLoofah thanks for tracking this down.

I think there *is* a snapshottest bug or mis-feature in [CollectionFormatter.normalize](https://github.com/syrusakbary/snapshottest/blob/48528b7679987c979c9fa4b8af1e57db601fdb2f/snapshottest/formatters.py#L48):

```python
class CollectionFormatter(TypeFormatter):
    def normalize(self, value, formatter):
        iterator = iter(value.items()) if isinstance(value, dict) else iter(value)
        # ... This line is the problem:
        return value.__class__([formatter.normalize(item) for item in iterator])
```

This is going to have problems with *all* collection subclasses that require additional parameters in their constructors. (And indeed, there's already an override for defaultdict.) 

At a minimum, CollectionFormatter.normalize should probably catch exceptions trying to re-construct a normalized object, and issue a more helpful error message (suggesting the user either convert the snapshotted object to a simpler type, or that they add a custom formatter). Ideally, snapshottest would also preflight this while writing snapshot files, so that the error is reported then, not only when comparing snapshots later.

But I'm wondering if a better fix might be to change the `value.__class__(...)` line to instead construct the base type the formatter writes into snapshots. E.g., `CollectionFormatter(dict, format_dict).normalize(value)` should just try to construct a plain dict—even if value is a DRF ReturnDict—because format_dict always just writes snapshots as plain dicts. Then we wouldn't need all these extra custom formatters: if a formatter is willing to write a snapshot, then it really should be able to compare the same type of object to that snapshot later.

(I confess I'm getting a little lost in understanding the need for this normalize logic in the first place. It transforms the *actual* value being compared (not the *expected* snapshot value) prior to comparison. I think this was added in #82 to fix problems introduced in a bunch of other major changes between v0.5.0 and v0.5.1.)

Also, it seems like the original report from @hobochild is probably related, but I think that specific case *might* be covered by the fix in #116 that went into v0.6.0.

**Comment by StoicLoofah** [comment]
@medmunds Agreed that better error messages could be helpful. Regarding a more complete fix, I did try using:

```python
return self.types([formatter.normalize(item) for item in iterator])
```

instead so that it would convert the `ReturnDict` into a `dict` as suggested. That did work for my case, but it failed the snapshottest unit tests

```
_____________________ test_snapshot_does_not_match_other_values[snapshot OrderedDict([('a', 1), ('b', 2), ('c', 3)]) shouldn't match OrderedDict([('c', 3), ('b', 2), ('a', 1)])] ______________________

snapshot_test = <test_snapshot_test.GenericSnapshotTest object at 0x107c31e10>, value = OrderedDict([('a', 1), ('b', 2), ('c', 3)]), other_value = OrderedDict([('c', 3), ('b', 2), ('a', 1)])

    @pytest.mark.parametrize(
        "value, other_value",
        [   
            pytest.param(
                value,
                other_value,
                id="snapshot {!r} shouldn't match {!r}".format(value, other_value),
            )
            for value in SNAPSHOTABLE_VALUES
            for other_value in SNAPSHOTABLE_VALUES
            if other_value != value
        ],
    )
    def test_snapshot_does_not_match_other_values(snapshot_test, value, other_value):
        # first run stores the value as the snapshot
        snapshot_test.assert_match(value)
        assert_snapshot_test_succeeded(snapshot_test)

        # second run tries to match other_value, should fail
        snapshot_test.reinitialize()
        with pytest.raises(AssertionError):
>           snapshot_test.assert_match(other_value)
E           Failed: DID NOT RAISE <class 'AssertionError'>

tests/test_snapshot_test.py:122: Failed
_____________________ test_snapshot_does_not_match_other_values[snapshot OrderedDict([('c', 3), ('b', 2), ('a', 1)]) shouldn't match OrderedDict([('a', 1), ('b', 2), ('c', 3)])] ______________________

snapshot_test = <test_snapshot_test.GenericSnapshotTest object at 0x107c71198>, value = OrderedDict([('c', 3), ('b', 2), ('a', 1)]), other_value = OrderedDict([('a', 1), ('b', 2), ('c', 3)])

    @pytest.mark.parametrize(
        "value, other_value",
        [   
            pytest.param(
                value,
                other_value,
                id="snapshot {!r} shouldn't match {!r}".format(value, other_value),
            )
            for value in SNAPSHOTABLE_VALUES
            for other_value in SNAPSHOTABLE_VALUES
            if other_value != value
        ],
    )
    def test_snapshot_does_not_match_other_values(snapshot_test, value, other_value):
        # first run stores the value as the snapshot
        snapshot_test.assert_match(value)
        assert_snapshot_test_succeeded(snapshot_test)

        # second run tries to match other_value, should fail
        snapshot_test.reinitialize()
        with pytest.raises(AssertionError):
>           snapshot_test.assert_match(other_value)
E           Failed: DID NOT RAISE <class 'AssertionError'>

tests/test_snapshot_test.py:122: Failed
```

I think that makes sense as a failure. It's possible we could get around that specific case by making another formatter for `OrderedDict`, but it's kind of a tradeoff between edge cases.

I realize I have mostly been investigating rather than implementing an actual fix, but I don't have a good intuition for what the *right* solution is. If you have a suggestion, though, I would be happy to take a shot at putting together a PR for it

**Comment by hobochild** [comment]
Thanks for looking into this. I can confirm I no longer get the original error on 0.6.0. I am now however hitting a geojson serializer issue. 

```
cls = <class 'geojson.geometry.Point'>, coords = ('type', 'Point')
precision = 6

    @classmethod
    def clean_coordinates(cls, coords, precision):
        if isinstance(coords, cls):
            return coords['coordinates']
    
        new_coords = []
        if isinstance(coords, Geometry):
            coords = [coords]
        for coord in coords:
            if isinstance(coord, (list, tuple)):
                new_coords.append(cls.clean_coordinates(coord, precision))
            elif isinstance(coord, Geometry):
                new_coords.append(coord['coordinates'])
            elif isinstance(coord, _JSON_compliant_types):
                new_coords.append(round(coord, precision))
            else:
>               raise ValueError("%r is not a JSON compliant number" % coord)
E               ValueError: 'type' is not a JSON compliant number
```

I'll investigate and try create a reproduction, but again I think it's unrelated to the original issue.

**Comment by StoicLoofah** [comment]
Coming back to my solution above

```
return self.types([formatter.normalize(item) for item in iterator])
```

I was able to get the tests fixed by adding another default formatter for `OrderedDict`

```
...
CollectionFormatter(OrderedDict, format_dict),
...
```

I think this change makes sense, but I am wary about unexpected side effects on other existing snapshots. Any thoughts about how dangerous that change would be?
